#!/bin/sh

. ${DIR_MELVABLE}/module/ubuntu_1404_64bit_mac/ubuntu_1404_64bit_mac.melvablesrc

Initialize
InstallDevelopTall
# InstallExplore
# InstallWatch
InstallOptimize
InstallTime
InstallSudo
# InstallServerLamp
