#!/bin/sh

. ../module/ubuntu_1404_64bit_mac/ubuntu_1404_64bit_mac.melvablesrc

Intialize
InstallDevelopTall
# InstallExplore
# InstallWatch
InstallOptimize
InstallTime
InstallSudo
# InstallServerLamp
